// VIDEO
export const LOAD_ALL_VIDEOS = 'LOAD_ALL_VIDEOS';
export const ALL_VIDEOS_LOADED = 'ALL_VIDEOS_LOADED';
export const LOAD_ALL_RELATED_VIDEOS = 'LOAD_ALL_RELATED_VIDEOS';
export const ALL_RELATED_VIDEOS_LOADED = 'ALL_RELATED_VIDEOS_LOADED';
export const LOAD_VIDEO = 'LOAD_VIDEO';
export const VIDEO_LOADED = 'VIDEO_LOADED';
export const VIDEO_ERROR = 'VIDEO_ERROR';
